import Head from "next/head";
import { Layout } from "../components/layout/Layout";

const Home = () => (
  <Layout>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="h-full w-full bg-red-500" />
  </Layout>
);

export default Home;
